import './tokens.css';
import './styles.css';
import './widgets/kpi/KpiWidget';
import './widgets/comparison/ComparisonWidget';
import './widgets/kpi-group/KpiGroupWidget';
import './widgets/bar/BarWidget';
import './widgets/line/LineWidget';
import './widgets/pie/PieWidget';
import './widgets/heatmap/HeatmapWidget';
import './widgets/table/TableWidget';
import './widgets/text/TextWidget';
import './widgets/note/NoteWidget';
import './widgets/status/StatusWidget';
import './widgets/gauge/GaugeWidget';
import './widgets/threshold-line/ThresholdLineWidget';
import './widgets/availability/AvailabilityGridWidget';

export { widgetRegistry, renderWidget, type WidgetDefinition } from './registry';
export type { Aggregation, WidgetConfig, WidgetData, WidgetProps, WidgetRender, WidgetSize } from './types';
export { KpiWidget } from './widgets/kpi/KpiWidget';
export { ComparisonWidget } from './widgets/comparison/ComparisonWidget';
export { KpiGroupWidget } from './widgets/kpi-group/KpiGroupWidget';
export { BarWidget } from './widgets/bar/BarWidget';
export { LineWidget } from './widgets/line/LineWidget';
export { PieWidget } from './widgets/pie/PieWidget';
export { HeatmapWidget } from './widgets/heatmap/HeatmapWidget';
export { TableWidget } from './widgets/table/TableWidget';
export { TextWidget } from './widgets/text/TextWidget';
export { NoteWidget } from './widgets/note/NoteWidget';
export { StatusWidget } from './widgets/status/StatusWidget';
export { GaugeWidget } from './widgets/gauge/GaugeWidget';
export { ThresholdLineWidget } from './widgets/threshold-line/ThresholdLineWidget';
export { AvailabilityGridWidget } from './widgets/availability/AvailabilityGridWidget';
